version: "3.5"

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'secret-chat'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
